# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."
# toolchain = "nightly-2021-08-16"
# docker_image = "thewawar/ckb-capsule:2021-08-16"

# capsule version
version = "0.6.0 b850e01"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "smt_contracts"
template_type = "Rust"

[[contracts]]
name = "cycles_rust"
template_type = "Rust"

[[contracts]]
name = "cycles_c"
template_type = "Rust"
