[package]
name = "cycles-lib"
version = "0.1.0"
edition = "2018"

[dependencies]
ckb-std = "0.7.1"
sparse-merkle-tree = { path = "../../deps/sparse-merkle-tree", default-features = false }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }

[build-dependencies]
cc = "1.0"
